### ISSUE TITLE
ダッシュボード Issue2 カテゴリ別の備品一覧

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1A#21]
## 終了条件

登録されているカテゴリのうち１つ以上の備品が存在するカテゴリが最大4件ずつ表示できること

**Comment by harukamiki** [comment]
- カテゴリの中に備品ない場合はカテゴリ欄ごと消す
- カテゴリ5つ以上なら、最新の4カテゴリのみ表示
