### ISSUE TITLE
備品一覧 Issue1 キーワードを入力して検索すると備品名の部分一致でヒットしたものの備品一覧を表示する

### ISSUE THREAD

**Issue by silent-bayline** [posse-ap/posse1-hackathon-202209-team1A#7]
## 終了条件

備品一覧の画面が作成されていること
画面に検索したキーワードと備品名の部分一致でマッチした備品のみが一覧表示されること
項目はマッチした件数、画像、カテゴリ名、備品名

## 備考

画面を新規作成

**Comment by Makiiiiii** [comment]
https://github.com/posse-ap/posse1-hackathon-202209-team1A/pull/35

こちらで対応済みです
